ACTIVATION: prelu
AUX_LOSS: true
AVDSUP_VAL: /home/jure/datasets/AVD/avdsup_val_coco_gt.json
AVD_TRAIN: /home/jure/datasets/AVD/avd_train_coco_gt.json
AVD_VAL: /home/jure/datasets/AVD/avd_val_coco_gt.json
BACKBONE:
  dilation: false
  lr: 1.0e-05
  name: resnet50
  pretrained: true
  return_intermediate_layers: true
BASE_LOSS: false
BASE_LOSS_LEVELS: 0
BATCH_SIZE: 1
COCO_PATH: /home/jure/datasets/COCO/images
DIM_FEEDFORWARD: 2048
DN_ARGS:
  BOX_NOISE_SCALE: 0.3
  LABEL_NOISE_SCALE: 0.2
  NUM_DN_GROUPS: 5
  USE_DN: true
  USE_DN_AUX: true
  USE_INDICATOR: false
DROPOUT: 0.0
D_MODEL: 256
EOS_COEF: 0.1
EPOCHS: 50
FOCAL_ALPHA: 0.25
GMUSUP_VAL: /home/jure/datasets/GMU_kitchens/gmusup_val_coco_gt.json
GMU_TRAIN: /home/jure/datasets/GMU_kitchens/gmu_train_coco_gt.json
GMU_VAL: /home/jure/datasets/GMU_kitchens/gmu_val_coco_gt.json
ICBIN_TRAIN_PATH: /home/jure/datasets/icbin/train
ICBIN_VAL_PATH: /home/jure/datasets/icbin/val
ICTRSUP_VAL: /home/jure/datasets/icbin/train/icbintrainsup_val_coco_gt.json
ICTR_TRAIN: /home/jure/datasets/icbin/train/icbintrain_train_coco_gt.json
ICTR_VAL: /home/jure/datasets/icbin/train/icbintrain_val_coco_gt.json
ICVALSUP_VAL: /home/jure/datasets/icbin/val/icbinvalsup_val_coco_gt.json
ICVAL_TRAIN: /home/jure/datasets/icbin/val/icbinval_train_coco_gt.json
ICVAL_VAL: /home/jure/datasets/icbin/val/icbinval_val_coco_gt.json
LMO_TRAIN_PATH: /home/jure/datasets/LMO/synthetic/lmo_train_coco_gt.json
LMO_VALBOP_PATH: /home/jure/datasets/LMO/val_bop/lmo_val_coco_gt.json
LMO_VAL_PATH: /home/jure/datasets/LMO/val/lmo_val2_coco_gt.json
LM_TRAIN_PATH: /home/jure/datasets/LM/synthetic/lm_train_coco_gt.json
LM_VALBOP_PATH: /home/jure/datasets/LM/val_bop/lm_val_coco_gt.json
LM_VAL_PATH: /home/jure/datasets/LM/val/lm_val_coco_gt.json
LOOK_FORWARD_TWICE: true
LOSS_CENTEREDNESS: 1.0
LOSS_CONTRASTIVE: 0.2
LOSS_WEIGHTS:
  loss_bbox: 5.0
  loss_ce: 1.0
  loss_giou: 2.0
  loss_sim: 1.0
LR: 0.0001
LR_DROP: 25
MAX_NORM: 0.1
MODULATE_HW_ATTN: true
NUM_DECODER_LAYERS: 6
NUM_ENCODER_LAYERS: 6
NUM_LEVELS: 2
NUM_QUERIES: 100
NUM_TGTS: 5
NUM_WORKERS: 0
N_HEADS: 8
OBJECTS_365_PATH: /home/jure/datasets/Objects365/data
PIN_MEMORY: true
POSITION_EMBEDDING: sine
QUERY_SCALE_TYPE: cond_elewise
SAVE_BEST_ONLY: false
SET_COST_BBOX: 5.0
SET_COST_CLASS: 1.0
SET_COST_GIOU: 2.0
SYNTHETIC_TRAIN_PATH: /home/jure/datasets/synthetic_dataset/synthetic_dataset_coco_gt.json
TEMPLATE_ENCODER:
  lr: 5.0e-06
  name: vits16
  pretrained: true
  use_checkpointing: true
TEST_DATASETS:
- /home/jure/datasets/LM/val_bop/lm_val_coco_gt.json
- /home/jure/datasets/LMO/val/lmo_val2_coco_gt.json
TGT_IMG_SIZE: 224
TGT_MAX_IMG_SIZE: 448
TGT_MIN_AREA: 500
TLESSSUP_VAL: /home/jure/datasets/T-LESS/tlesssup_val_coco_gt.json
TLESS_TRAIN: /home/jure/datasets/T-LESS/tless_train_coco_gt.json
TLESS_VAL: /home/jure/datasets/T-LESS/tless_val_coco_gt.json
TRAIN_DATASETS:
- /home/jure/datasets/AVD/avd_train_coco_gt.json
- /home/jure/datasets/GMU_kitchens/gmu_train_coco_gt.json
- /home/jure/datasets/T-LESS/tless_train_coco_gt.json
- /home/jure/datasets/ycbv_processed/ycbv_train_coco_gt.json
- /home/jure/datasets/synthetic_dataset/synthetic_dataset_coco_gt.json
TRAIN_METHOD: both
TWO_STAGE: false
WEIGHT_DECAY: 0.0001
YCBVSUP_VAL: /home/jure/datasets/ycbv_processed/ycbvsup_val_coco_gt.json
YCBV_TRAIN: /home/jure/datasets/ycbv_processed/ycbv_train_coco_gt.json
YCBV_VAL: /home/jure/datasets/ycbv_processed/ycbv_val_coco_gt.json
